title: "Recipe Book"
description: "A GitHub Pages recipe book"
baseurl: ""
url: ""
collections:
  recipes:
    output: true
collections_dir: source
defaults:
  - scope:
      path: ""
      type: "recipes"
    values:
      layout: "recipe"
      type: "categories"
    values:
      layout: "category"
  - scope:
      path: ""
      type: "recipes"
    values:
      layout: "recipe"
